### ISSUE TITLE
[PE-D] When using addMod to add a module, if the link part is added, an error will occur

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-3/tp#177]
steps to reproduce
type in `addMod n/cs2040 l/https://ay2122s1-cs2103t-w11-3.github.io/tp/UserGuide.html`
the software says Names should only contain alphanumeric characters and spaces, and it should not be blank

expected:
the command should be executed and the mod should be added

screenshot

![image.png](https://raw.githubusercontent.com/Li-Lehao/ped/main/files/2f6cee79-2f13-4bb5-8353-3fe3856ddfd2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Li-Lehao/ped#7

**Comment by JinxinZhao315** [comment]
Repeated bug
