### ISSUE TITLE
[PE-D] listLink command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-3/tp#186]
# Description:
`listLink`  returns "Unknown command' as error message

# Steps to reproduce:
1. `findLink testlink`
2. `listLink`

# Expected:
Full list of links showed again
# Actual:
Error message
# Screenshots:

![image.png](https://raw.githubusercontent.com/LZher385/ped/main/files/263855e2-304c-4471-a2fe-1adfe6f08eb7.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: LZher385/ped#7

**Comment by markuslim24** [comment]
fixed
