### ISSUE TITLE
[PE-D] Able to add module without link

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-3/tp#187]
Steps to reproduce:

1. Execute `addMod n/a`

Expected behaviour:

Module not added, since link must be present

Actual behaviour:

![image.png](https://raw.githubusercontent.com/Chang-CH/ped/main/files/31ab4478-8761-48b3-925e-fdc42fe926f2.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Chang-CH/ped#6

**Comment by JinxinZhao315** [comment]
Repeated bug
