### ISSUE TITLE
[PE-D] Difference in help command between UG and v1.3

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-3/tp#198]
The screenshot for the help command in the UG is outdated and is different from the one in v1.3.

UG:

![Screen Shot 2021-10-29 at 17.04.56.png](https://raw.githubusercontent.com/kevinmingtarja/ped/master/files/c3d9e286-e4d0-480f-a07f-f8abfb2d9d3e.png)

v1.3:

![Screen Shot 2021-10-29 at 17.04.40.png](https://raw.githubusercontent.com/kevinmingtarja/ped/master/files/43979cb7-8e66-43d9-8df8-955fec349d6e.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: kevinmingtarja/ped#9

**Comment by markuslim24** [comment]
Duplicate
