### ISSUE TITLE
[PE-D] Date in title of the calendar section does not change

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-3/tp#201]
# Description:
Date in the title of the calendar section does not change when `readDay` is used. It remains at `2021-10-29` no matter what I do.
# Steps to reproduce:
`readDay 2021-10-26`
# Expected:
Date in the title to chnage to "2021-10-26"
# Actual:
Date remains at "2021-10-29"
# Screenshots:

![image.png](https://raw.githubusercontent.com/LZher385/ped/main/files/3b61ac77-416d-4a89-b19d-f36e1e1edbf3.png)

# Recommendations:
The value could have possibly been hard-coded/referring to today's date (I'm not sure)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LZher385/ped#13

**Comment by markuslim24** [comment]
Fixed.
